---
- name: Frontal provision
  hosts: frontal
  sudo: yes
  roles:
    - repos
    - apache
    - php
    - mysql
    - libraries

- name: Development specific provision
  hosts: development
  sudo: yes
  roles:
    - dev