---
- name: Set PHP error reporting
  ini_file: dest=/etc/php5/apache2/php.ini
            section=PHP
            option=error_reporting
            value={{php_error_reporting}}
  notify:
    - restart apache2

- name: Set PHP display errors
  ini_file: dest=/etc/php5/apache2/php.ini
            section=PHP
            option=display_errors
            value={{php_display_errors}}
  notify:
    - restart apache2

- name: Set PHP display startup errors
  ini_file: dest=/etc/php5/apache2/php.ini
            section=PHP
            option=display_startup_errors
            value={{php_display_errors}}
  notify:
    - restart apache2

- name: Set PHP timezone
  ini_file: dest=/etc/php5/apache2/php.ini
            section=PHP
            option=date.timezone
            value={{php_timezone}}
  notify:
    - restart apache2