---
# tasks file for php

- name: Install PHP
  apt: pkg=php5 state=latest
  notify:
    - restart apache2

- name: Install PHP Extensions
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-curl
  notify:
    - restart apache2

- include: configure.yml