---
- name: Set Db hosts pointing localhost
  template:
    src=hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/bin

- name: Install Git
  apt: pkg=git state=present