---
- name: Set Db hosts pointing localhost
  template:
    src=hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/bin

- name: Install Git
  apt: pkg=git state=present

- name: Check APACHE_RUN_USER
  shell: grep -c 'APACHE_RUN_USER=www-data' /etc/apache2/envvars
  register: check_apache_run_user
  ignore_errors: true

- name: Check APACHE_RUN_GROUP
  shell: grep -c 'APACHE_RUN_GROUP=www-data' /etc/apache2/envvars
  register: check_apache_run_group
  ignore_errors: true

- name: Set APACHE_RUN_USER=vagrant in Apache envvars
  shell: sed -i 's/APACHE_RUN_USER=www-data/APACHE_RUN_USER=vagrant/' /etc/apache2/envvars
  when: check_apache_run_user.stdout > "0"

- name: Set APACHE_RUN_GROUP=vagrant in Apache envvars
  shell: sed -i 's/APACHE_RUN_GROUP=www-data/APACHE_RUN_GROUP=vagrant/' /etc/apache2/envvars
  when: check_apache_run_group.stdout > "0"