---
# tasks needed libraries

- name: Download wkHtmlToPDF
  shell: wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb -O /tmp/wkhtmltox.deb

- name: Install Libraries
  apt: pkg={{ item }} state=latest
  with_items:
    - xfonts-75dpi

- name: Install wkHtmlToPDF
  shell: dpkg -i /tmp/wkhtmltox.deb