---
# tasks needed libraries

- name: Download wkHtmlToPDF
  shell: wget http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb -O /tmp/wkhtmltox.deb

- name: Install wkHtmlToPDF
  shell: dpkg -i /tmp/wkhtmltox.deb