Crm\AppBundle\Entity\Company:
    type: entity
    table: company
    repositoryClass: Crm\AppBundle\Entity\CompanyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        taxCode:
            type: string
            length: 255
            column: tax_code
        address:
            type: string
            length: 255
        city:
            type: string
            length: 255
        zipCode:
            type: string
            length: '5'
            column: zip_code
        email:
            type: string
            length: 255
        phone:
            type: string
            length: '12'
        fax:
            type: string
            length: '12'
            nullable: true
        website:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
    manyToOne:
        country:
            targetEntity: Country
            joinColumn:
                name: id_country
                referencedColumnName: id
        province:
            targetEntity: Province
            joinColumn:
                name: id_province
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: id_user
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [onPrePersist]
        preUpdate: [onPreUpdate]
