# tasks file for mysql

- name: Install MySQL Server
  apt: pkg=mysql-server state=latest

- name: Install MySQL modules
  apt: pkg={{ item }} state=latest
  with_items:
   - php5-mysql
   - python-mysqldb
  notify:
    - restart apache2

- name: Enable runlevel to defaults
  command: update-rc.d mysql defaults

- name: Ensure is running
  service:
    name: mysql
    state: started