<?php

namespace Crm\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * Get list of companies filtered and paginated.
     *
     * @param int $page Current page.
     * @param int $page_size Number of items per page.
     * @return Paginator
     */
    public function getCompaniesList($page=1, $page_size = 10) {
        $dql = <<<'DQL'
SELECT c FROM
    CrmAppBundle:company c
DQL;

        $query = $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult( $page_size * ( $page - 1 ) )
            ->setMaxResults( $page_size );

        return new Paginator($query);
    }
}
