<?php

namespace Crm\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceDetailRepository extends EntityRepository
{
}
