<?php

namespace Crm\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
    public function getNextReferenceNumber()
    {
        $reference_slug = date('Y');

        $dql = <<<DQL
SELECT
    i.reference
FROM
    CrmAppBundle:Invoice i
WHERE
    i.reference LIKE :reference_slug
ORDER BY
    i.reference DESC
DQL;

        $result = $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults(1)
            ->setParameter('reference_slug', $reference_slug.'%')
            ->getOneOrNullResult();

        if (empty($result['reference'])) {
            return $reference_slug.'001';
        }else{
            $number = str_replace($reference_slug, '', $result['reference']);
            $number++;
            $number = str_pad($number, 3, '0', STR_PAD_LEFT);

            return $reference_slug.$number;
        }
    }
}
